@echo off
setlocal EnableDelayedExpansion

echo.
echo ═══════════════════════════════════════════════
echo          RUBIX FRESH INSTALL
echo ═══════════════════════════════════════════════
echo.

REM Get source directory (where this script lives)
set "SOURCE_DIR=%~dp0"
set "SOURCE_DIR=%SOURCE_DIR:~0,-1%"

REM Prompt for target directory
set /p "TARGET_DIR=Enter target directory (e.g., C:\projects\my-app\rubix): "

if "%TARGET_DIR%"=="" (
    echo ERROR: No directory specified.
    pause
    exit /b 1
)

REM Create target if it doesn't exist
if not exist "%TARGET_DIR%" (
    echo Creating directory: %TARGET_DIR%
    mkdir "%TARGET_DIR%"
)

echo.
echo Source: %SOURCE_DIR%
echo Target: %TARGET_DIR%
echo.
echo This will copy a CLEAN god-agent (no secrets, no data).
echo.
pause

REM Copy source files (excluding large/sensitive directories)
echo.
echo [1/4] Copying source files...
robocopy "%SOURCE_DIR%\src" "%TARGET_DIR%\src" /E /NFL /NDL /NJH /NJS
robocopy "%SOURCE_DIR%\docs" "%TARGET_DIR%\docs" /E /NFL /NDL /NJH /NJS 2>nul

REM Copy individual files
echo        Copying package files...
copy "%SOURCE_DIR%\package.json" "%TARGET_DIR%\" >nul
copy "%SOURCE_DIR%\tsconfig.json" "%TARGET_DIR%\" >nul
copy "%SOURCE_DIR%\.env.example" "%TARGET_DIR%\" >nul 2>nul

REM Copy launchers (except install.bat itself to avoid recursion issues)
echo        Copying launcher scripts...
copy "%SOURCE_DIR%\launch.bat" "%TARGET_DIR%\" >nul 2>nul
copy "%SOURCE_DIR%\launch-telegram.bat" "%TARGET_DIR%\" >nul 2>nul
copy "%SOURCE_DIR%\launch-daemon.bat" "%TARGET_DIR%\" >nul 2>nul
copy "%SOURCE_DIR%\launch-webhooks.bat" "%TARGET_DIR%\" >nul 2>nul
copy "%SOURCE_DIR%\assimilate.bat" "%TARGET_DIR%\" >nul 2>nul

REM Copy documentation
echo        Copying documentation...
copy "%SOURCE_DIR%\*.md" "%TARGET_DIR%\" >nul 2>nul
copy "%SOURCE_DIR%\HELP.txt" "%TARGET_DIR%\" >nul 2>nul

REM Create empty data directory
echo [2/4] Creating data directory...
mkdir "%TARGET_DIR%\data" 2>nul

REM Install dependencies
echo [3/4] Installing dependencies (this may take a few minutes)...
cd /d "%TARGET_DIR%"
call npm install

if %ERRORLEVEL% neq 0 (
    echo ERROR: npm install failed!
    pause
    exit /b 1
)

REM Build
echo [4/7] Building TypeScript...
call npm run build

if %ERRORLEVEL% neq 0 (
    echo ERROR: Build failed!
    pause
    exit /b 1
)

REM Copy non-TypeScript files to dist (schema.sql, etc.)
echo        Copying SQL schemas...
if not exist "%TARGET_DIR%\dist\storage" mkdir "%TARGET_DIR%\dist\storage"
copy "%TARGET_DIR%\src\storage\*.sql" "%TARGET_DIR%\dist\storage\" >nul 2>nul

REM Configure API keys
echo.
echo [5/7] Configuring API keys...
echo.
echo ═══════════════════════════════════════════════
echo          API KEY CONFIGURATION
echo ═══════════════════════════════════════════════
echo.
echo You need API keys from:
echo   OpenAI:    https://platform.openai.com/api-keys
echo   Anthropic: https://console.anthropic.com/
echo.
echo Leave blank to skip (you can add later in .env)
echo.

set /p "OPENAI_KEY=OpenAI API Key (for embeddings): "
set /p "ANTHROPIC_KEY=Anthropic API Key (for CODEX): "

REM Create .env file
echo [6/7] Creating .env file...
(
echo # RUBIX Environment Configuration
echo # Generated by install.bat
echo.
echo # Required: OpenAI API key for embeddings ^(768-dim vectors^)
echo OPENAI_API_KEY=%OPENAI_KEY%
echo.
echo # Required: Anthropic API key for CODEX code generation
echo ANTHROPIC_API_KEY=%ANTHROPIC_KEY%
echo.
echo # Data directory ^(relative to RUBIX folder^)
echo GOD_AGENT_DATA_DIR=./data
echo.
echo # Optional: Telegram bot token for notifications
echo # TELEGRAM_BOT_TOKEN=
echo.
echo # Optional: Model settings
echo # RUBIX_MODEL=claude-sonnet-4-20250514
echo # RUBIX_MAX_PARALLEL=5
) > "%TARGET_DIR%\.env"

echo        Created .env with your API keys

REM Run assimilate
echo.
echo [7/7] Running assimilation...
echo.
call node dist\cli\index.js assimilate --skip-setup -y

if %ERRORLEVEL% neq 0 (
    echo.
    echo WARNING: Assimilation had issues. You may need to run it manually:
    echo   cd "%TARGET_DIR%"
    echo   node dist\cli\index.js assimilate
    echo.
)

echo.
echo ═══════════════════════════════════════════════
echo          RUBIX INSTALLATION COMPLETE
echo ═══════════════════════════════════════════════
echo.
echo Location: %TARGET_DIR%
echo.
echo RUBIX is ready! To use with Claude Code:
echo   1. Open your project in Claude Code
echo   2. RUBIX MCP server will auto-connect
echo.
echo Manual commands:
echo   Launch MCP:      node dist\mcp-server.js
echo   Launch Telegram: launch-telegram.bat
echo   Re-assimilate:   node dist\cli\index.js assimilate
echo.
pause
